// eslint-disable-next-line import/no-extraneous-dependencies
import { createEnv } from '@t3-oss/env-nextjs';

import { ADDRESS, ONLY_BOOLEAN, STRING_NOT_EMPTY } from '@/lib/zod';

export const envs = createEnv({
  client: {
    // RainbowKit
    NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID: STRING_NOT_EMPTY,

    // Tenderly
    NEXT_PUBLIC_TENDERLY_PROJECT_ID: STRING_NOT_EMPTY,
    NEXT_PUBLIC_TENDERLY_VNETS_ENABLED: ONLY_BOOLEAN,
    NEXT_PUBLIC_ENABLE_TESTNETS: ONLY_BOOLEAN,

    // Etherscan
    NEXT_PUBLIC_ETHERSCAN_API_KEY: STRING_NOT_EMPTY,

    // Contract Addresses
    NEXT_PUBLIC_BRIDGE_SEPOLIA_ADDRESS: ADDRESS,
    NEXT_PUBLIC_BRIDGE_BSCSCAN_ADDRESS: ADDRESS,
  },
  runtimeEnv: {
    // RainbowKit
    NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID:
      process.env.NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID,

    // Tenderly
    NEXT_PUBLIC_TENDERLY_PROJECT_ID:
      process.env.NEXT_PUBLIC_TENDERLY_PROJECT_ID,
    NEXT_PUBLIC_TENDERLY_VNETS_ENABLED:
      process.env.NEXT_PUBLIC_TENDERLY_VNETS_ENABLED,
    NEXT_PUBLIC_ENABLE_TESTNETS: process.env.NEXT_PUBLIC_ENABLE_TESTNETS,

    // Etherscan
    NEXT_PUBLIC_ETHERSCAN_API_KEY: process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY,
    NEXT_PUBLIC_BRIDGE_SEPOLIA_ADDRESS:
      process.env.NEXT_PUBLIC_BRIDGE_SEPOLIA_ADDRESS,
    NEXT_PUBLIC_BRIDGE_BSCSCAN_ADDRESS:
      process.env.NEXT_PUBLIC_BRIDGE_BSCSCAN_ADDRESS,
  },
  emptyStringAsUndefined: true,
});
